const UserActionTypes = {
    SET_QUERY: 'SET_QUERY',
    SET_TAB: 'SET_TAB',
    GET_SHOW_USER_START: 'GET_SHOW_USER_START',
    GET_SHOW_USER_SUCCESS: 'GET_SHOW_USER_SUCCESS',
    GET_SHOW_USER_FAILURE: 'GET_SHOW_USER_FAILURE',
    SEARCH_USERS_START: 'SEARCH_USERS_START',
    SEARCH_USERS_SUCCESS: 'SEARCH_USERS_SUCCESS',
    SEARCH_USERS_FAILURE: 'SEARCH_USERS_FAILURE',
    CLEAR_USERS: 'CLEAR_USERS',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    LOG_IN_START: 'LOG_IN_START',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_IN_FAILURE: 'LOG_IN_FAILURE',
    LOG_OUT_START: 'LOG_OUT_START',
    LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
    LOG_OUT_FAILURE: 'LOG_OUT_FAILURE',
};

export default UserActionTypes;
